apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: ingress-patch.yaml

images:
  - name: ghcr.io/ganesandhakshinamurthy/sample-end-to-end-backend
    newTag: latest
  - name: ghcr.io/ganesandhakshinamurthy/sample-end-to-end-frontend
    newTag: latest
